### ISSUE TITLE
copepod.yml

### ISSUE THREAD

**Issue by bjarneo** [bjarneo/copepod#3]
Should it be possible to define a yml file copepod reads from?

Example
```yml
# Deployment configuration
host: example.com
user: deploy
image: my-app
dockerfile: Dockerfile
tag: latest
platform: linux/amd64
sshKey: ~/.ssh/id_rsa
containerName: my-app
containerPort: "3000"
hostPort: "3000"
envFile: .env.production

# Build arguments
buildArgs:
  VERSION: "1.0.0"
  ENV: production
  GIT_HASH: ${GIT_HASH} 
  
# Custom remote exec commands (new possible feature)
remoteCommands:
  - "apt update"
  - "apt upgrade"
```
